services:
  kmserver:
    build: .
    image: registry.gitlab.com/karaokemugen/code/karaokemugen-server:${TAG}
    container_name: kmserver
    hostname: kmserver
    # Change this in your .env
    environment:
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
      TAG: latest
    ports:
      - 1350:80
    volumes:
      - ./app:/srv/kmserver/app

  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: karaokemugen_server
      POSTGRES_PASSWORD: blabla
      POSTGRES_DB: karaokemugen_server
    volumes:
      - ./docker/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - ./app/database:/var/lib/postgresql/data

