import Vue from 'vue';
import { config, library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon, FontAwesomeLayers } from '@fortawesome/vue-fontawesome';
import {
	faList,
	faTags,
	faFileImport,
	faLaptop,
	faChalkboardTeacher,
	faUserSecret,
	faQuestionCircle,
	faTag,
	faBox,
	faUpload,
	faCircle,
	faPlay,
	faTasks,
	faTv,
	faGlobe,
	faMicrophoneAlt,
	faSignature,
	faPhotoVideo,
	faProjectDiagram,
	faChess,
	faSignInAlt,
	faSignOutAlt,
	faEdit,
	faCloudDownloadAlt,
	faStar,
	faFileExport,
	faMeh,
	faMusic,
	faDatabase,
	faCloudUploadAlt,
	faUser,
	faBoxes,
	faLanguage,
	faCalendarAlt,
	faPen,
	faLock,
	faFolderPlus,
	faEraser,
	faPlus,
	faClosedCaptioning,
	faExternalLinkAlt,
	faFileVideo,
	faClock,
	faTachometerAlt
} from '@fortawesome/free-solid-svg-icons';

// This is important, we are going to let Nuxt.js worry about the CSS
config.autoAddCss = false;

library.add(
	faList,
	faTags,
	faFileImport,
	faLaptop,
	faChalkboardTeacher,
	faUserSecret,
	faQuestionCircle,
	faTag,
	faBox,
	faUpload,
	faCircle,
	faPlay,
	faTasks,
	faTv,
	faGlobe,
	faMicrophoneAlt,
	faSignature,
	faPhotoVideo,
	faProjectDiagram,
	faChess,
	faSignInAlt,
	faSignOutAlt,
	faEdit,
	faCloudDownloadAlt,
	faStar,
	faFileExport,
	faMeh,
	faMusic,
	faDatabase,
	faCloudUploadAlt,
	faUser,
	faBoxes,
	faLanguage,
	faCalendarAlt,
	faPen,
	faLock,
	faFolderPlus,
	faEraser,
	faPlus,
	faClosedCaptioning,
	faExternalLinkAlt,
	faFileVideo,
	faClock,
	faTachometerAlt);

// Register the component globally
Vue.component('font-awesome-icon', FontAwesomeIcon);
Vue.component('font-awesome-layers', FontAwesomeLayers);
