ALTER TABLE inbox ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'sent';
ALTER TABLE inbox ADD COLUMN IF NOT EXISTS reject_reason TEXT;
ALTER TABLE inbox ADD COLUMN IF NOT EXISTS history JSONB[];
ALTER TABLE inbox ADD COLUMN IF NOT EXISTS modified_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE users ADD COLUMN IF NOT EXISTS contributor_trust_level INTEGER NOT NULL DEFAULT 1;

UPDATE users SET contributor_trust_level = 1;