App:
  InstanceID: changeit_InstanceID
  JwtSecret: changeit_JwtSecret
System:
  Database:
    username: changeit_username
    password: changeit_password
    host: localhost
    database: changeit_database
    port: 5432
  Binaries:
    ffmpeg:
      Linux: /usr/bin/ffmpeg
  Repositories:
    - Name: mugen.re
      Online: true
      Enabled: true
      BaseDir: 'data/git'
      Path:
        Medias:
          - data/medias
    - Name: Staging
      Online: false
      Enabled: true
      BaseDir: 'staging/git'
      Path:
        Medias:
          - staging/medias
Frontend:
  Port: changeit_FrontendPort
API:
  Host: changeit_APIHost
  Port: 80
Hardsub:
  Enabled: false
Users:
  Enabled: true
Shortener:
  Enabled: true
Stats:
  Enabled: true
KaraExplorer:
  MediaLinks: true
  Import: true
  Suggestions: true
  InProgressSongsList: changeit_karaokebase/-/issues?scope=all&state=opened&label_name[]=Doing
  Secure: false
  DiscourseURL: https://discourse.karaokes.moe
  DiscordURL: https://karaokes.moe/discord
Gitlab:
  Enabled: changeit_GitlabEnabled
  Token: changeit_GitlabToken
  Host: changeit_GitlabHost
  ProjectID: changeit_GitlabProjectId
