import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { 
	faTasks,
	faPlay,
	faIgloo,
	faTags,
	faTag,
	faMicrophoneAlt,
	faTv,
	faSignature,
	faChalkboardTeacher,
	faUserSecret,
	faLanguage,
	faCalendarAlt,
	faGlobe,
	faFileImport,
	faBox,
	faBoxes,
	faPhotoVideo,
	faProjectDiagram,
	faChess,
	faLaptop,
	faTimes,
	faCheck
	} from '@fortawesome/free-solid-svg-icons'
import { faCreativeCommonsSampling } from '@fortawesome/free-brands-svg-icons'

export default {
	home: <FontAwesomeIcon icon={faIgloo} />,
	karas: <FontAwesomeIcon icon={faCreativeCommonsSampling} />,
	kara: <FontAwesomeIcon icon={faCreativeCommonsSampling} />,
	tags: <FontAwesomeIcon icon={faTags} />,
	tag: <FontAwesomeIcon icon={faTag} />,
	miscs: <FontAwesomeIcon icon={faTags} />,
	misc: <FontAwesomeIcon icon={faTag} />,
	singers: <FontAwesomeIcon icon={faMicrophoneAlt} />,
	singer: <FontAwesomeIcon icon={faMicrophoneAlt} />,
	series: <FontAwesomeIcon icon={faTv} />,
	serie: <FontAwesomeIcon icon={faTv} />,
	songwriters: <FontAwesomeIcon icon={faSignature} />,
	songwriter: <FontAwesomeIcon icon={faSignature} />,
	creators: <FontAwesomeIcon icon={faChalkboardTeacher} />,
	creator: <FontAwesomeIcon icon={faChalkboardTeacher} />,
	authors: <FontAwesomeIcon icon={faUserSecret} />,
	author: <FontAwesomeIcon icon={faUserSecret} />,
	languages: <FontAwesomeIcon icon={faLanguage} />,
	language: <FontAwesomeIcon icon={faGlobe} />,
	years: <FontAwesomeIcon icon={faCalendarAlt} />,
	year: <FontAwesomeIcon icon={faCalendarAlt} />,
	video_play: <FontAwesomeIcon icon={faPlay} />,
	kara_import: <FontAwesomeIcon icon={faFileImport} />,
	songtype: <FontAwesomeIcon icon={faTasks} />,
	songtypes: <FontAwesomeIcon icon={faTasks} />,
	group: <FontAwesomeIcon icon={faBox} />,
	groups: <FontAwesomeIcon icon={faBoxes} />,
	family: <FontAwesomeIcon icon={faPhotoVideo} />,
	families: <FontAwesomeIcon icon={faPhotoVideo} />,
	origin: <FontAwesomeIcon icon={faProjectDiagram} />,
	origins: <FontAwesomeIcon icon={faProjectDiagram} />,
	genre: <FontAwesomeIcon icon={faChess} />,
	genres: <FontAwesomeIcon icon={faChess} />,
	platform: <FontAwesomeIcon icon={faLaptop} />,
	platforms: <FontAwesomeIcon icon={faLaptop} />,
	abort: <FontAwesomeIcon icon={faTimes} />,
	confirm: <FontAwesomeIcon icon={faCheck} />
}